**Решения второго занятия**

Дан произвольный список из чисел, надо переставить элементы так чтобы сначала шли нули, потом отрицательные числа а затем положительные числа.

In [3]:
lst = [1, 2, 3, 0, -1, 0, -4, 5]

zeros_count = 0

for i, val in enumerate(lst):
    if val == 0:
        zeros_count += 1
        lst.pop(i)
        lst.insert(0, 0)
    if val < 0:
        lst.pop(i)
        lst.insert(zeros_count, val)

print(lst)

[0, 0, -4, -1, 1, 2, 3, 5]


<img src="11.19.png">

In [9]:
from random import randint

lst = [randint(0,10) for i in range(10)]
print("получен список ", lst)


k1 = int(input("Введите k1:"))
k2 = int(input("Введите k2:"))

res = 0
print(sum(lst[k1:k2+1]))

получен список  [8, 9, 3, 0, 8, 8, 4, 3, 6, 1]


Введите k1: 3
Введите k2: 5


16


11.20

In [11]:
from random import randint

lst = [randint(0,10) for i in range(3)]
print("получен список ", lst)

z = 1
res = 0
for val in lst:
    res += val*z
    z *= -1

print(res)

получен список  [8, 4, 7]
11


12.28

мое природное решение

In [64]:
import numpy as np


arr_dim = 9
res = np.ones((arr_dim,arr_dim))

curr_ax_len = res.shape[0]
layers_count = (curr_ax_len//2)+1 # сколько "слоев" в матрице
num = 1
big_sum = 0


a = 0
for i, layer in enumerate(range(arr_dim,1,-2)):
    # заполнение каждого квадратика
    for j in range(layer - 1):
        # верхняя крышка
        res[i, j + i] = (j+1) + big_sum
        # правая крышка
        res[j + i, arr_dim - 1 - i] = (j+1)+(layer-1)+big_sum
        # нижняя крышка
        res[arr_dim - 1 - i, arr_dim - j - i - 1] = (j+1)+(layer-1)*2 + big_sum
        # правая крышка
        res[arr_dim - 1 - j - i, i] = (j+1) + (layer-1)*3 + big_sum
        a += 1
    big_sum += (j+1) + (layer-1)*3

res[arr_dim//2, arr_dim//2] = big_sum + 1
print(res)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [32. 33. 34. 35. 36. 37. 38. 39. 10.]
 [31. 56. 57. 58. 59. 60. 61. 40. 11.]
 [30. 55. 72. 73. 74. 75. 62. 41. 12.]
 [29. 54. 71. 80. 81. 76. 63. 42. 13.]
 [28. 53. 70. 79. 78. 77. 64. 43. 14.]
 [27. 52. 69. 68. 67. 66. 65. 44. 15.]
 [26. 51. 50. 49. 48. 47. 46. 45. 16.]
 [25. 24. 23. 22. 21. 20. 19. 18. 17.]]


Решение подсказанное преподавателем

In [81]:
s = 6
res = np.ones((s,s))

x = 0
y = 0
num = 1

for x in range(x,s):
    res[y,x] = num
    x += 1
    num += 1
for  y < s-1:
    res[y,x] = num
    y += 1
    num += 1

# while True:
#     # верхняя крышка
#     for x in range(x,s):
#         res[y,x] = num
#         x += 1
#         num += 1
#     while y < s-1:
#         res[y,x] = num
#         y += 1
#         num += 1
#     # while x > 0:
#     #     res[y,x] = num
#     #     num += 1
#     #     x -= 1
#     # while y > 0:
#     #     res[y,x] = num
#     #     num += 1
#     #     y -= 1

# print(res)

[[1. 2. 3. 4. 5. 6.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Заполнить главную и побочную диагонали

In [ ]:
import numpy as np

s = 7
np.ones()

Функция формат

In [67]:
"Приве {} как {}".format(3,4)

'Приве 3 как 4'

Фунция `get` для соловаря

In [ ]:
a = {"A1"}

In [88]:
a = dict(b = 4, a = 3, g = 3)
a.popitem()

('g', 3)