**Занятие с урока 11**

# Исключения

In [1]:
100/0

ZeroDivisionError: division by zero

In [2]:
try:
    k = 1/0
except ZeroDivisionError:
    k = 0

In [6]:
f = open("1.txt")

print(f.readlines())

f.close()

[]


In [24]:
from tkinter import * 

def is_number():
    num_str = number_entry.get()
    lab.text = "text"
    try:
        int(num_str)
    except ValueError:
        lab["text"] = "не номер телефона"
    else:
        lab["text"] = "номер телефона"
    
        

root = Tk()

number_entry = Entry()
number_entry.pack()

Button(
    text = "прочитать",
    command = is_number
).pack()

lab = Label()
lab.pack()

root.mainloop()

Сколько раз `numpy` массиве пменяется знак у радом стоящих элементов.

In [50]:
import numpy as np

np.random.seed(12)
arr = np.random.uniform(-10, 10, 20)
print(arr)
print("Знак поменялся", ((arr < 0)[:-1] == (arr>0)[1:]).sum(), " раз")

[-6.91674315  4.80099393 -4.7336997   0.67478787 -9.70850075  8.37494016
  8.01429708 -9.33157145  9.13898673 -7.25581357 -4.32343294  2.12166369
  8.88450272  7.05471082 -9.95481533  0.42452054  1.04075267 -0.29245173
  5.36268308 -6.78566494]
Знак поменялся 14  раз


# tasks

In [58]:
print("task1")
arr = np.zeros(10)
print(arr)

print("task2")
arr = np.ones(10)
print(arr)

print("tak3")
arr = np.full(10, 2.5)
print(arr)

task1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
task2
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tak3
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [61]:
print("task4")
?np.add

task4


Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            ~/.local/lib/python3.10/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out`

In [98]:
print("task 5")
arr = np.zeros(10)
arr[5] = 1
print(arr)


print("task 6")
arr = np.arange(10,3, -1)
print(arr)

print("task 7")
print(arr[-1:0:-1])

print("task 8")
print(np.arange(9).reshape((3,3)))

print("task 9")
print(np.nonzero(np.array([1,2,0,0,4,0]) == 0))

print("task 10")
print(np.eye(3))

print("task 11")
print(np.random.random((3,3)))

print("task 12")
arr = np.random.random((10,10))
print(arr)
print("min value ",np.min(arr))
print("max value ",np.max(arr))

print("task 13")
arr = np.random.random(30)
print(np.mean(arr))

task 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
task 6
[10  9  8  7  6  5  4]
task 7
[4 5 6 7 8 9]
task 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]
task 9
(array([2, 3, 5]),)
task 10
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
task 11
[[0.87994694 0.34658845 0.25715505]
 [0.74557377 0.13702096 0.52315191]
 [0.92504158 0.29199682 0.75085446]]
task 12
[[0.40645545 0.83856696 0.74595091 0.02679529 0.89411953 0.16855882
  0.88023412 0.39565265 0.05240425 0.88258981]
 [0.63265342 0.28979325 0.86748162 0.25908067 0.32930207 0.55406916
  0.60187364 0.47049711 0.79150439 0.54117784]
 [0.6623366  0.07865777 0.90451762 0.08088102 0.6897408  0.61773164
  0.25662017 0.99974193 0.85928714 0.47576185]
 [0.99871231 0.40341725 0.43493026 0.68844672 0.26414166 0.44112577
  0.67182194 0.24284481 0.44604563 0.09623104]
 [0.94941861 0.61369983 0.14021858 0.55618071 0.07422679 0.44898437
  0.83515269 0.64666376 0.3977416  0.64446166]
 [0.9274893  0.22679055 0.89703511 0.25500486 0.62183603 0.14788346
  0.49377664 0.94777116 0.45072491 

In [116]:
np.ndarray([5,6])

array([[4.68802266e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 9.15047025e-310, 1.16097020e-028],
       [8.26219736e-072, 2.92732920e-028, 2.00190962e-076,
        1.04917183e-153, 5.23081515e-143, 1.74491063e-076],
       [1.14394186e-071, 4.03820833e-037, 3.45065517e-032,
        8.07137840e-144, 3.59751658e+252, 1.46901661e+179],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        9.97076651e-047, 4.65623715e-033, 5.64281142e-091],
       [7.46413349e-038, 8.38305949e+165, 5.04621343e+180,
        1.94918963e-153, 1.14484251e+243, 2.59903827e-144]])

In [111]:
list_of_arrs = [np.ndarray([1,2,3,4,5]), np.ndarray([1,2,3,4,5]), np.ndarray([1,2,3,4,5])]
list_of_arrs
# [list_of_arrs[0]] + list(map(lambda x: x[1:], list_of_arrs[1:]))

[array([[[[[6.92055191e-310, 6.92055191e-310, 4.68746330e-310,
            4.68746330e-310, 6.92050147e-310],
           [6.92054069e-310, 6.92054062e-310, 6.92050163e-310,
            6.92054069e-310, 6.92054062e-310],
           [6.92050147e-310, 6.92054069e-310, 6.92054062e-310,
            6.92050163e-310, 6.92054069e-310],
           [6.92054062e-310, 6.92050147e-310, 6.92054069e-310,
            6.92054062e-310, 6.92050163e-310]],
 
          [[6.92054069e-310, 6.92054062e-310, 6.92050147e-310,
            6.92054069e-310, 6.92054062e-310],
           [6.92054069e-310, 6.92054062e-310, 6.92050163e-310,
            6.92054069e-310, 6.92054062e-310],
           [6.92050147e-310, 6.92054069e-310, 6.92054062e-310,
            6.92050163e-310, 6.92054069e-310],
           [6.92054062e-310, 6.92050147e-310, 6.92054069e-310,
            6.92054062e-310, 6.92050163e-310]],
 
          [[6.92054069e-310, 6.92054062e-310, 6.92050147e-310,
            6.92054069e-310, 6.92054062e-310],
    

In [123]:
s = np.array([-12, 5, -6, 9 , -7, 6, 8, -4, 9 , -4])

((s[1:]*s[:-1]) < 0).sum()

8