**Лекция с урока 10 `numpy`**

In [1]:
import numpy as np

`np.empty` - создаст массив без заполнения, т.е. память занимаемая этим массивом не изменяется.

In [3]:
np.empty((3,3))

array([[4.63649636e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

`np.fromfunction` - создаст массив в с использованием функции

In [5]:
np.fromfunction(lambda i, j: i*3 + j, (4,4))

array([[ 0.,  1.,  2.,  3.],
       [ 3.,  4.,  5.,  6.],
       [ 6.,  7.,  8.,  9.],
       [ 9., 10., 11., 12.]])

In [8]:
# np.ones((100,100)).set_pritoptioins()
lst = [1,3,4]
np.array(lst)

array([1, 3, 4])

In [19]:
list(np.zeros((10,10)))

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [38]:
arr = np.random.choice([1,2,3,4,5], 500, p = [0.2]*5)
print("Получен массив")
print(arr)
print("Число уникальных элементов ", len(np.unique(arr)))

Получен массив
[4 1 2 5 1 5 5 1 4 1 3 2 2 3 4 5 4 3 3 5 5 2 2 4 5 1 4 5 2 2 2 2 5 1 1 4 3
 3 3 4 5 1 5 5 5 4 3 1 1 1 2 3 1 3 2 2 2 4 4 5 1 5 5 2 2 3 3 1 4 2 1 4 4 4
 4 2 5 4 3 4 3 5 2 1 3 1 4 4 1 3 1 4 1 1 1 2 2 1 4 5 2 2 2 3 5 2 3 1 4 1 2
 2 3 5 3 2 2 5 2 1 1 3 2 2 5 2 5 4 3 3 4 2 1 2 2 4 3 3 1 5 5 4 5 1 4 3 1 2
 3 3 2 3 5 2 5 3 3 1 2 1 3 2 3 1 1 3 5 3 3 4 2 5 2 2 4 2 2 5 3 2 2 2 5 4 1
 4 5 2 5 1 5 5 3 3 5 5 2 5 5 3 2 5 1 5 1 1 4 2 3 1 4 4 1 5 2 1 4 5 1 1 1 1
 5 1 4 5 2 3 5 3 5 3 5 1 3 5 5 5 4 1 5 2 2 3 1 1 2 3 2 2 2 2 3 1 4 2 5 3 3
 3 2 4 4 4 2 3 4 4 5 1 2 4 3 1 4 4 2 2 2 3 5 3 4 1 3 5 2 1 1 3 3 1 4 1 1 5
 5 5 1 1 3 1 5 2 3 5 2 2 3 2 2 1 3 3 2 1 5 5 5 2 3 4 3 1 4 2 4 5 4 1 5 4 1
 2 4 5 5 5 3 4 3 2 4 3 4 4 1 1 1 4 2 5 2 4 5 3 3 5 4 1 2 5 4 1 3 3 2 4 2 1
 1 3 1 5 3 5 4 1 5 5 1 5 3 4 5 2 5 1 3 5 5 2 5 2 5 1 1 4 5 1 5 2 3 5 5 1 1
 1 4 4 5 2 3 4 5 2 2 3 4 3 3 4 4 2 4 1 5 2 4 5 2 3 3 3 1 3 3 2 1 1 4 4 4 2
 3 2 2 3 4 3 1 5 4 3 5 1 2 1 3 4 4 4 3 5 5 5 2 2 1 2 3 2 4 2 4 5 2 3 4 2 4
 1 2 1 1 1

`set_printoptions`

In [130]:
arr = np.random.rand(1000)

np.set_printoptions(precision = 5)
print("precision = 5")
print(arr)

np.set_printoptions(precision = 2)
print("precision = 2")
print(arr)

precision = 5
[0.95632 0.7579  0.46938 0.72354 0.21308 ... 0.92085 0.7888  0.26299
 0.69425 0.32401]
precision = 2
[0.96 0.76 0.47 0.72 0.21 ... 0.92 0.79 0.26 0.69 0.32]


In [143]:
arr = np.zeros((100,100))
np.set_printoptions(threshold = 1)
print("threshold = 1")
print(arr)
np.set_printoptions(threshold = 10000)
print("threshold = 100")
print(arr)

threshold = 1
[[0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. ... 0. 0. 0. 0. 0.]]
threshold = 100
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [66]:
arr = np.random.rand(100)
np.set_printoptions(
    threshold = 1,
    edgeitems = 3
)

print("edgeitems = 3")
print(arr)

np.set_printoptions(
    edgeitems = 5
)
print("edgeitems = 5")
print(arr)

edgeitems = 3
[0.06 0.08 0.47 ... 0.96 0.51 0.89]
edgeitems = 5
[0.06 0.08 0.47 0.7  0.81 ... 0.31 0.34 0.96 0.51 0.89]


In [80]:
arr = np.random.rand(100)
np.set_printoptions(
    threshold = 100,
    linewidth = 50,
    precision = 3
)
print("linewidth = 50")
print(arr)

np.set_printoptions(
    linewidth = 20
)
print("linewidth = 20")
print(arr)

linewidth = 50
[0.384 0.522 0.447 0.929 0.367 0.238 0.085 0.942
 0.506 0.624 0.373 0.326 0.355 0.698 0.177 0.246
 0.456 0.412 0.159 0.271 0.437 0.163 0.531 0.722
 0.657 0.505 0.646 0.016 0.051 0.625 0.821 0.336
 0.583 0.601 0.389 0.208 0.712 0.259 0.337 0.231
 0.893 0.067 0.734 0.94  0.884 0.842 0.418 0.162
 0.227 0.509 0.835 0.18  0.097 0.698 0.084 0.218
 0.906 0.989 0.4   0.498 0.453 0.375 0.885 0.105
 0.206 0.34  0.059 0.203 0.163 0.527 0.526 0.11
 0.423 0.84  0.528 0.187 0.64  0.828 0.764 0.254
 0.24  0.241 0.304 0.462 0.335 0.678 0.211 0.957
 0.913 0.188 0.572 0.138 0.478 0.639 0.59  0.729
 0.965 0.961 0.154 0.303]
linewidth = 20
[0.384 0.522 0.447
 0.929 0.367 0.238
 0.085 0.942 0.506
 0.624 0.373 0.326
 0.355 0.698 0.177
 0.246 0.456 0.412
 0.159 0.271 0.437
 0.163 0.531 0.722
 0.657 0.505 0.646
 0.016 0.051 0.625
 0.821 0.336 0.583
 0.601 0.389 0.208
 0.712 0.259 0.337
 0.231 0.893 0.067
 0.734 0.94  0.884
 0.842 0.418 0.162
 0.227 0.509 0.835
 0.18  0.097 0.698
 0.084 0.218 0.

In [95]:
arr = np.random.rand(100)/100

np.set_printoptions(
    linewidth = 74,
    suppress = True
)

print("suppress = True")
print(arr)


np.set_printoptions(
    suppress = False
)
print("suppress = False")
print(arr)

suppress = True
[0.005 0.004 0.009 0.003 0.    0.002 0.005 0.001 0.004 0.01  0.008 0.002
 0.003 0.007 0.006 0.009 0.003 0.005 0.01  0.009 0.001 0.001 0.001 0.004
 0.001 0.005 0.009 0.01  0.004 0.002 0.002 0.008 0.008 0.008 0.002 0.002
 0.009 0.007 0.001 0.    0.001 0.001 0.004 0.007 0.004 0.006 0.007 0.004
 0.008 0.002 0.007 0.007 0.001 0.005 0.003 0.001 0.006 0.01  0.001 0.
 0.007 0.006 0.002 0.009 0.008 0.006 0.01  0.009 0.006 0.005 0.001 0.001
 0.005 0.01  0.004 0.004 0.002 0.007 0.006 0.005 0.002 0.009 0.004 0.003
 0.002 0.01  0.001 0.008 0.007 0.001 0.002 0.002 0.007 0.007 0.001 0.003
 0.003 0.01  0.009 0.009]
suppress = False
[4.825e-03 4.478e-03 8.909e-03 3.474e-03 1.611e-04 1.841e-03 4.675e-03
 9.334e-04 3.897e-03 9.566e-03 8.213e-03 2.252e-03 2.823e-03 7.087e-03
 6.420e-03 9.020e-03 2.830e-03 4.841e-03 9.871e-03 9.008e-03 1.185e-03
 1.116e-03 5.674e-04 3.835e-03 5.365e-04 4.534e-03 8.906e-03 9.993e-03
 4.175e-03 1.669e-03 2.136e-03 8.335e-03 7.939e-03 8.070e-03 1.635e-03
 1.66

In [145]:
def test_func(i, j):
    val = i+j
    return np.where(
        val %2 == 0,
        np.NaN, val
    )
    
arr = np.fromfunction(test_func, (4,4))

np.set_printoptions(
    nanstr = "nan"
)
print("nanstr = nan")
print(arr)


np.set_printoptions(
    nanstr = "hello"
)
print("nanstr = hello")
print(arr)

nanstr = nan
[[nan  1. nan  3.]
 [ 1. nan  3. nan]
 [nan  3. nan  5.]
 [ 3. nan  5. nan]]
nanstr = hello
[[hello    1. hello    3.]
 [   1. hello    3. hello]
 [hello    3. hello    5.]
 [   3. hello    5. hello]]


In [150]:
np.set_printoptions(
    infstr = "бесконечность"
)
np.array([np.inf])

array([бесконечность])

найти самую длинную группу подряд идущих положительных элементов массива;

In [210]:
np.random.seed(10)
arr = np.random.uniform(-10, 10, 20)


cs_res = (arr<0).cumsum()
ind = np.argmax(np.unique(cs_res, return_counts=True)[1])
arr[cs_res == ind][1:]

array([0.2438452677, 6.252419233 , 2.2505213366, 4.4351063486])